# Generated by Django 5.1.4 on 2025-01-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_product_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
